server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# срок истечения токена, после него нужно будет снова авторизоваться
app.jwt.secret=change-me-to-a-very-long-secret-key-at-least-32-bytes-long-for-hs256
app.jwt.expiration-ms=86400000

# Папка для загрузок
app.upload.dir=uploads
# Базовый URL для отдачи (фронт склеит)
app.upload.base-url=http://localhost:8082/uploads
# Максимальный размер файла (5 МБ)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB